name: Version Tagging

on:
  push:
    branches:
      - main
    paths:
      - 'lib/sidekiq_retry_strategy/version.rb'

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Get current version
        id: get_version
        run: echo "::set-output name=version::$(ruby -r ./lib/sidekiq_retry_strategy/version -e 'puts SidekiqRetryStrategy::VERSION')"
      - name: Increment version
        id: increment_version
        run: |
          current_version=${{ steps.get_version.outputs.version }}
          IFS='.' read -r -a version_parts <<< "$current_version"
          version_parts[2]=$((version_parts[2] + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"
      - name: Update version file
        run: |
          new_version=${{ steps.increment_version.outputs.new_version }}
          echo $new_version > VERSION
          sed -i "s/VERSION = .*/VERSION = '$new_version'/g" lib/sidekiq_retry_strategy/version.rb
      - name: Commit version bump
        run: |
          git add VERSION lib/sidekiq_retry_strategy/version.rb
          git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }}"
          git push origin main
      - name: Create tag
        run: |
          new_version=${{ steps.increment_version.outputs.new_version }}
          git tag v$new_version
          git push origin v$new_version